# Generated by Django 4.1.2 on 2022-10-31 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name_plural": "Amenities",
            },
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name_plural": "Facilities",
            },
        ),
        migrations.CreateModel(
            name="HouseRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name": "House Rule",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="", max_length=180)),
                (
                    "description",
                    models.TextField(blank=True, max_length=150, null=True),
                ),
                (
                    "country",
                    models.CharField(default="United States of America", max_length=80),
                ),
                ("city", models.CharField(default="Los Angeles", max_length=80)),
                ("address", models.CharField(default="", max_length=250)),
                ("price", models.PositiveIntegerField()),
                ("guests", models.PositiveIntegerField()),
                ("beds", models.PositiveIntegerField()),
                ("bedrooms", models.PositiveIntegerField()),
                ("bathrooms", models.PositiveIntegerField()),
                ("check_in", models.TimeField()),
                ("check_out", models.TimeField()),
                ("instant_book", models.BooleanField(default=False)),
                ("pet_friendly", models.BooleanField(default=True)),
                (
                    "type_of_place",
                    models.CharField(
                        choices=[
                            ("entire_place", "Entire Place"),
                            ("private_room", "Private Room"),
                            ("shared_room", "Shared Room"),
                            ("hotel_room", "Hotel Room"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("entire_place", "Entire Place"),
                            ("private_room", "Private Room"),
                            ("shared_room", "Shared Room"),
                            ("hotel_room", "Hotel Room"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amenities",
                    models.ManyToManyField(
                        blank=True, related_name="amenities", to="rooms.amenity"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="categories",
                        to="categories.category",
                    ),
                ),
                (
                    "facilities",
                    models.ManyToManyField(
                        blank=True, related_name="facilities", to="rooms.facility"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
