# Generated by Django 4.1.3 on 2022-11-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('guesthouse', 'Guesthouse'), ('hotel', 'Hotel')], max_length=20),
        ),
    ]
