# Generated by Django 4.1.2 on 2022-10-31 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category_type",
                    models.CharField(
                        choices=[("rooms", "Rooms"), ("experiences", "Experiences")],
                        max_length=15,
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
    ]
